# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './calki.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelPoczatek = QtWidgets.QLabel(self.centralwidget)
        self.labelPoczatek.setGeometry(QtCore.QRect(10, 0, 151, 61))
        self.labelPoczatek.setObjectName("labelPoczatek")
        self.labelKoniec = QtWidgets.QLabel(self.centralwidget)
        self.labelKoniec.setGeometry(QtCore.QRect(10, 50, 151, 61))
        self.labelKoniec.setObjectName("labelKoniec")
        self.labelIle = QtWidgets.QLabel(self.centralwidget)
        self.labelIle.setGeometry(QtCore.QRect(10, 100, 151, 61))
        self.labelIle.setObjectName("labelIle")
        self.lineEditPoczatek = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPoczatek.setGeometry(QtCore.QRect(130, 10, 141, 41))
        self.lineEditPoczatek.setObjectName("lineEditPoczatek")
        self.lineEditKoniec = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditKoniec.setGeometry(QtCore.QRect(130, 60, 141, 41))
        self.lineEditKoniec.setObjectName("lineEditKoniec")
        self.lineEditIle = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditIle.setGeometry(QtCore.QRect(130, 110, 141, 41))
        self.lineEditIle.setObjectName("lineEditIle")
        self.guzik = QtWidgets.QPushButton(self.centralwidget)
        self.guzik.setGeometry(QtCore.QRect(300, 10, 221, 141))
        self.guzik.setObjectName("guzik")
        self.labelResult = QtWidgets.QLabel(self.centralwidget)
        self.labelResult.setGeometry(QtCore.QRect(20, 170, 501, 101))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.labelResult.setFont(font)
        self.labelResult.setAlignment(QtCore.Qt.AlignCenter)
        self.labelResult.setObjectName("labelResult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelPoczatek.setText(_translate("MainWindow", "Początek przedziału"))
        self.labelKoniec.setText(_translate("MainWindow", "Koniec przedziału"))
        self.labelIle.setText(_translate("MainWindow", "Ilość podprzedziałów"))
        self.guzik.setText(_translate("MainWindow", "Oblicz"))
        self.labelResult.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
